CREATE DATABASE IF NOT EXISTS zoo;

USE zoo;

CREATE TABLE animal_specie (
    ID INT NOT NULL AUTO_INCREMENT,
    SPECIE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=INNODB;

CREATE TABLE animal_location (
    ID INT NOT NULL AUTO_INCREMENT,
    LOCATION VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=INNODB;

CREATE TABLE employee_manager (
    ID INT NOT NULL AUTO_INCREMENT,
    MANAGER VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=INNODB;

CREATE TABLE animal_employee (
    ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE VARCHAR(100) NOT NULL,
    MANAGER_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES employee_manager(id)
) ENGINE=INNODB;

CREATE TABLE animal (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    SPECIE_ID INT NOT NULL,
    SEX VARCHAR(6) NOT NULL,
    AGE INT NOT NULL,
    LOCATION_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SPECIE_ID) REFERENCES animal_specie(id),
    FOREIGN KEY (LOCATION_ID) REFERENCES animal_location(id),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES animal_employee(id)
) ENGINE=INNODB;